// Auto-generated. Do not edit!

// (in-package ros_base_learning.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class CounterGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.target_number = null;
    }
    else {
      if (initObj.hasOwnProperty('target_number')) {
        this.target_number = initObj.target_number
      }
      else {
        this.target_number = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type CounterGoal
    // Serialize message field [target_number]
    bufferOffset = _serializer.int32(obj.target_number, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type CounterGoal
    let len;
    let data = new CounterGoal(null);
    // Deserialize message field [target_number]
    data.target_number = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'ros_base_learning/CounterGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '5e5331756d1685bdff28b9bf94bf4c45';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Goal: 定义我们想让服务器实现的目标
    int32 target_number
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new CounterGoal(null);
    if (msg.target_number !== undefined) {
      resolved.target_number = msg.target_number;
    }
    else {
      resolved.target_number = 0
    }

    return resolved;
    }
};

module.exports = CounterGoal;
