<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="PI" value="3.14159265359"/>
    
    <xacro:property name="base_radius" value="0.12" /> <!-- 圆柱体车身的半径 -->
    <xacro:property name="base_height" value="0.1" />  <!-- 圆柱体车身的高度 -->
    <xacro:property name="base_link_mass" value="1.5" /> <!-- 质量 kg -->

    <!-- 驱动轮属性 -->
    <xacro:property name="wheel_radius" value="0.070" /> <!-- 半径 m -->
    <xacro:property name="wheel_length" value="0.04" /> <!-- 宽度 m -->
    <xacro:property name="wheel_mass" value="0.15" /> 
    <!-- 关键修改: 轮子Y轴位置现在基于车身半径计算 -->
    <xacro:property name="wheel_joint_y" value="${base_radius + wheel_length/2}" /> <!-- Y轴偏移 -->

    <!-- 万向轮属性 -->
    <xacro:property name="caster_radius" value="0.025" />
    <xacro:property name="caster_mass" value="0.05" />
    
    <!-- 雷达属性 -->
    <xacro:property name="lidar_size" value="0.05"/>
    <xacro:property name="lidar_mass" value="0.2"/>
    
    <!-- 引入底盘和雷达的宏文件 -->
    <xacro:include filename="$(find robot_simulation)/urdf/car_base.xacro" />
    <xacro:include filename="$(find robot_simulation)/urdf/rplidar.xacro" />

    <!-- 创建一个虚拟的 base_footprint 作为根link -->
    <link name="base_footprint"/>

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>
    
    <!-- 实例化机器人底盘 -->
    <xacro:car_base />
    
    <!-- 实例化激光雷达 -->
    <xacro:rplidar />

    <!-- 连接雷达和车体 -->
    <joint name="laser_joint" type="fixed">
        <parent link="base_link"/>
        <child link="laser_link"/>
        <!-- 将雷达放置在圆柱体车身的顶部中心 -->
        <origin xyz="0 0 ${base_height/2 + lidar_size/4}" rpy="0 0 0"/>
    </joint>

</robot>