<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- 引入惯性宏文件 -->
    <xacro:include filename="$(find robot_simulation)/urdf/inertia.xacro" />
    
    <!-- 宏: RPLIDAR A1 -->
    <!-- 注意: 所有的属性<property>标签都已移至顶层robot.xacro文件 -->
    <xacro:macro name="rplidar">
        <link name="laser_link">
            <visual>
                <geometry>
                    <mesh filename="package://robot_simulation/meshes/rplidar.dae"/>
                </geometry>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${lidar_size/2}" length="${lidar_size/2}"/>
                </geometry>
            </collision>
            <xacro:cylinder_inertial m="${lidar_mass}" r="${lidar_size/2}" h="${lidar_size/2}"/>
        </link>

        <!-- Gazebo 激光雷达插件 -->
        <gazebo reference="laser_link">
            <sensor type="ray" name="rplidar_sensor">
                <pose>0 0 0 0 0 0</pose>
                <visualize>true</visualize>
                <update_rate>10</update_rate>
                <ray>
                    <scan>
                        <horizontal>
                            <samples>360</samples>
                            <resolution>1</resolution>
                            <min_angle>-${PI}</min_angle>
                            <max_angle>${PI}</max_angle>
                        </horizontal>
                    </scan>
                    <range>
                        <min>0.15</min>
                        <max>12.0</max>
                        <resolution>0.01</resolution>
                    </range>
                    <noise>
                        <type>gaussian</type>
                        <mean>0.0</mean>
                        <stddev>0.01</stddev>
                    </noise>
                </ray>
                <plugin name="gazebo_ros_laser_controller" filename="libgazebo_ros_laser.so">
                    <topicName>/scan</topicName>
                    <frameName>laser_link</frameName>
                </plugin>
            </sensor>
        </gazebo>
    </xacro:macro>
</robot>