<?xml version="1.0"?>
<robot name="car_chassis_2diff" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- 包含惯性计算宏 -->
    <xacro:include filename="$(find urdf_learning)/urdf/inertia_macros.xacro"/>

    <!-- ============================ PROPERTY LIST (保持不变) ============================ -->
    <xacro:property name="PI" value="3.14159265359"/>
    <xacro:property name="base_radius" value="0.17"/>
    <xacro:property name="base_height" value="0.08"/>
    <xacro:property name="wheel_radius" value="0.035"/> <!-- 修正: 与之前代码统一 -->
    <xacro:property name="wheel_length" value="0.02"/>
    <xacro:property name="caster_radius" value="0.01"/>
    <xacro:property name="base_mass" value="2.0"/>
    <xacro:property name="wheel_mass" value="0.05"/>
    <xacro:property name="motor_mass" value="0.1"/>
    <xacro:property name="caster_mass" value="0.05"/>
    <xacro:property name="motor_joint_x" value="-0.03"/>
    <xacro:property name="motor_joint_y" value="0.1"/>
    <xacro:property name="motor_joint_z" value="-0.02"/>
    <xacro:property name="wheel_joint_y" value="0.025"/>
    <xacro:property name="caster_joint_x" value="0.1"/>
    <xacro:property name="caster_joint_z" value="-0.04"/>

    <!-- ============================ COMPONENT MACRO DEFINITIONS ============================ -->
    <!-- 【修正】将所有组件宏的定义都放在顶层 -->

    <!-- *** Macro for robot base and footprint *** -->
    <xacro:macro name="base_footprint_and_chassis">
        <link name="base_footprint"/>
        <link name="base_link">
            <visual>
                <geometry><cylinder length="${base_height}" radius="${base_radius}"/></geometry>
                <material name="yellow"><color rgba="0.9 0.9 0.1 0.5"/></material>
            </visual>
            <collision>
                <geometry><cylinder length="${base_height}" radius="${base_radius}"/></geometry>
            </collision>
            <xacro:cylinder_inertial m="${base_mass}" r="${base_radius}" h="${base_height}"/>
        </link>
        <gazebo reference="base_link"><material>Gazebo/Yellow</material></gazebo>
        <joint name="base_footprint_joint" type="fixed">
            <parent link="base_footprint"/>
            <child link="base_link"/>
            <origin xyz="0 0 ${wheel_radius}"/>
        </joint>
    </xacro:macro>

    <!-- *** Macro for robot wheel (motor + wheel) *** -->
    <xacro:macro name="wheel_assembly" params="prefix y_reflect">
        <link name="${prefix}_motor">
            <inertial>
                <mass value="${motor_mass}"/>
                <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
            </inertial>
        </link>
        <joint name="${prefix}_motor_joint" type="fixed">
            <parent link="base_link"/>
            <child link="${prefix}_motor"/>
            <origin xyz="${motor_joint_x} ${y_reflect*motor_joint_y} ${motor_joint_z}"/>
        </joint>

        <link name="${prefix}_wheel_link">
            <visual>
                <origin rpy="${PI/2} 0 0"/>
                <geometry><cylinder radius="${wheel_radius}" length="${wheel_length}"/></geometry>
                <material name="black"><color rgba="0.1 0.1 0.1 1"/></material>
            </visual>
            <collision>
                <origin rpy="${PI/2} 0 0"/>
                <geometry><cylinder radius="${wheel_radius}" length="${wheel_length}"/></geometry>
            </collision>
            <xacro:cylinder_inertial m="${wheel_mass}" r="${wheel_radius}" h="${wheel_length}"/>
        </link>
        <gazebo reference="${prefix}_wheel_link"><material>Gazebo/Black</material></gazebo>

        <joint name="${prefix}_wheel_joint" type="continuous">
            <parent link="${prefix}_motor"/>
            <child link="${prefix}_wheel_link"/>
            <origin xyz="0 ${y_reflect*wheel_joint_y} 0"/>
            <axis xyz="0 1 0"/>
        </joint>
    </xacro:macro>

    <!-- *** Macro for robot caster *** -->
    <xacro:macro name="caster">
        <link name="caster_link">
            <visual>
                <geometry><sphere radius="${caster_radius}"/></geometry>
                <material name="black"/>
            </visual>
            <collision>
                <geometry><sphere radius="${caster_radius}"/></geometry>
            </collision>
            <xacro:sphere_inertial m="${caster_mass}" r="${caster_radius}"/>
        </link>
        <gazebo reference="caster_link"><material>Gazebo/Black</material></gazebo>
        <joint name="caster_joint" type="fixed">
            <parent link="base_link"/>
            <child link="caster_link"/>
            <origin xyz="${caster_joint_x} 0 ${caster_joint_z}"/>
        </joint>
    </xacro:macro>

    <!-- ============================ ASSEMBLY MACRO ============================ -->
    <!-- 【修正】这个宏只负责调用(实例化)上面定义的组件 -->
    <xacro:macro name="car_chassis_2diff">
        <xacro:base_footprint_and_chassis/>
        <xacro:wheel_assembly prefix="lf" y_reflect="1" />
        <xacro:wheel_assembly prefix="rt" y_reflect="-1" />
        <xacro:caster/>

        <gazebo>
            <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
                <alwaysOn>true</alwaysOn>
                <updateRate>100</updateRate>
                <leftJoint>lf_wheel_joint</leftJoint>
                <rightJoint>rt_wheel_joint</rightJoint>
                <wheelSeparation>${2 * (motor_joint_y + wheel_joint_y)}</wheelSeparation>
                <wheelDiameter>${2 * wheel_radius}</wheelDiameter>
                <torque>5</torque>
                <commandTopic>cmd_vel</commandTopic>
                <odometryTopic>odom</odometryTopic>
                <odometryFrame>odom</odometryFrame>
                <robotBaseFrame>base_footprint</robotBaseFrame>
                <!-- 
                  修改 1: 禁用插件发布轮子关节的TF。
                  将这个任务完全交给 robot_state_publisher，消除关于轮子的TF冲突。
                -->
                <publishWheelJointState>false</publishWheelJointState>
                
                <!-- 
                  修改 2: 明确指定插件发布 odom -> base_footprint 的TF。
                  虽然这是默认行为，但明确写出来可以避免歧义，并有助于调试。
                  这个参数在不同ROS版本中可能有不同名称，publishTf 是较新的名称。
                -->
                <publishTf>1</publishTf>
            </plugin>
        </gazebo>
    </xacro:macro>
</robot>