// Generated by gencpp from file ros_base_learning/CounterGoal.msg
// DO NOT EDIT!


#ifndef ROS_BASE_LEARNING_MESSAGE_COUNTERGOAL_H
#define ROS_BASE_LEARNING_MESSAGE_COUNTERGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_base_learning
{
template <class ContainerAllocator>
struct CounterGoal_
{
  typedef CounterGoal_<ContainerAllocator> Type;

  CounterGoal_()
    : target_number(0)  {
    }
  CounterGoal_(const ContainerAllocator& _alloc)
    : target_number(0)  {
  (void)_alloc;
    }



   typedef int32_t _target_number_type;
  _target_number_type target_number;





  typedef boost::shared_ptr< ::ros_base_learning::CounterGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_base_learning::CounterGoal_<ContainerAllocator> const> ConstPtr;

}; // struct CounterGoal_

typedef ::ros_base_learning::CounterGoal_<std::allocator<void> > CounterGoal;

typedef boost::shared_ptr< ::ros_base_learning::CounterGoal > CounterGoalPtr;
typedef boost::shared_ptr< ::ros_base_learning::CounterGoal const> CounterGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_base_learning::CounterGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_base_learning::CounterGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_base_learning::CounterGoal_<ContainerAllocator1> & lhs, const ::ros_base_learning::CounterGoal_<ContainerAllocator2> & rhs)
{
  return lhs.target_number == rhs.target_number;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_base_learning::CounterGoal_<ContainerAllocator1> & lhs, const ::ros_base_learning::CounterGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_base_learning

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_base_learning::CounterGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_base_learning::CounterGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_base_learning::CounterGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_base_learning::CounterGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_base_learning::CounterGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_base_learning::CounterGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_base_learning::CounterGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5e5331756d1685bdff28b9bf94bf4c45";
  }

  static const char* value(const ::ros_base_learning::CounterGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5e5331756d1685bdULL;
  static const uint64_t static_value2 = 0xff28b9bf94bf4c45ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_base_learning::CounterGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_base_learning/CounterGoal";
  }

  static const char* value(const ::ros_base_learning::CounterGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_base_learning::CounterGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal: 定义我们想让服务器实现的目标\n"
"int32 target_number\n"
;
  }

  static const char* value(const ::ros_base_learning::CounterGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_base_learning::CounterGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CounterGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_base_learning::CounterGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_base_learning::CounterGoal_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "target_number: ";
    Printer<int32_t>::stream(s, indent + "  ", v.target_number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_BASE_LEARNING_MESSAGE_COUNTERGOAL_H
