// Generated by gencpp from file ros_base_learning/CounterFeedback.msg
// DO NOT EDIT!


#ifndef ROS_BASE_LEARNING_MESSAGE_COUNTERFEEDBACK_H
#define ROS_BASE_LEARNING_MESSAGE_COUNTERFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_base_learning
{
template <class ContainerAllocator>
struct CounterFeedback_
{
  typedef CounterFeedback_<ContainerAllocator> Type;

  CounterFeedback_()
    : current_number(0)  {
    }
  CounterFeedback_(const ContainerAllocator& _alloc)
    : current_number(0)  {
  (void)_alloc;
    }



   typedef int32_t _current_number_type;
  _current_number_type current_number;





  typedef boost::shared_ptr< ::ros_base_learning::CounterFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_base_learning::CounterFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct CounterFeedback_

typedef ::ros_base_learning::CounterFeedback_<std::allocator<void> > CounterFeedback;

typedef boost::shared_ptr< ::ros_base_learning::CounterFeedback > CounterFeedbackPtr;
typedef boost::shared_ptr< ::ros_base_learning::CounterFeedback const> CounterFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_base_learning::CounterFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_base_learning::CounterFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_base_learning::CounterFeedback_<ContainerAllocator1> & lhs, const ::ros_base_learning::CounterFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.current_number == rhs.current_number;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_base_learning::CounterFeedback_<ContainerAllocator1> & lhs, const ::ros_base_learning::CounterFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_base_learning

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_base_learning::CounterFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_base_learning::CounterFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_base_learning::CounterFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_base_learning::CounterFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_base_learning::CounterFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_base_learning::CounterFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_base_learning::CounterFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a34d09927bdf6eea84e4ff079b190b1d";
  }

  static const char* value(const ::ros_base_learning::CounterFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa34d09927bdf6eeaULL;
  static const uint64_t static_value2 = 0x84e4ff079b190b1dULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_base_learning::CounterFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_base_learning/CounterFeedback";
  }

  static const char* value(const ::ros_base_learning::CounterFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_base_learning::CounterFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Feedback: 任务执行过程中周期性返回的数据\n"
"int32 current_number\n"
;
  }

  static const char* value(const ::ros_base_learning::CounterFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_base_learning::CounterFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CounterFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_base_learning::CounterFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_base_learning::CounterFeedback_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "current_number: ";
    Printer<int32_t>::stream(s, indent + "  ", v.current_number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_BASE_LEARNING_MESSAGE_COUNTERFEEDBACK_H
