// Generated by gencpp from file ros_base_learning/CounterResult.msg
// DO NOT EDIT!


#ifndef ROS_BASE_LEARNING_MESSAGE_COUNTERRESULT_H
#define ROS_BASE_LEARNING_MESSAGE_COUNTERRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_base_learning
{
template <class ContainerAllocator>
struct CounterResult_
{
  typedef CounterResult_<ContainerAllocator> Type;

  CounterResult_()
    : final_count(0)  {
    }
  CounterResult_(const ContainerAllocator& _alloc)
    : final_count(0)  {
  (void)_alloc;
    }



   typedef int32_t _final_count_type;
  _final_count_type final_count;





  typedef boost::shared_ptr< ::ros_base_learning::CounterResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_base_learning::CounterResult_<ContainerAllocator> const> ConstPtr;

}; // struct CounterResult_

typedef ::ros_base_learning::CounterResult_<std::allocator<void> > CounterResult;

typedef boost::shared_ptr< ::ros_base_learning::CounterResult > CounterResultPtr;
typedef boost::shared_ptr< ::ros_base_learning::CounterResult const> CounterResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_base_learning::CounterResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_base_learning::CounterResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_base_learning::CounterResult_<ContainerAllocator1> & lhs, const ::ros_base_learning::CounterResult_<ContainerAllocator2> & rhs)
{
  return lhs.final_count == rhs.final_count;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_base_learning::CounterResult_<ContainerAllocator1> & lhs, const ::ros_base_learning::CounterResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_base_learning

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_base_learning::CounterResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_base_learning::CounterResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_base_learning::CounterResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_base_learning::CounterResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_base_learning::CounterResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_base_learning::CounterResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_base_learning::CounterResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eaae876f57686d9f2a92f60bfbd26c85";
  }

  static const char* value(const ::ros_base_learning::CounterResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeaae876f57686d9fULL;
  static const uint64_t static_value2 = 0x2a92f60bfbd26c85ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_base_learning::CounterResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_base_learning/CounterResult";
  }

  static const char* value(const ::ros_base_learning::CounterResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_base_learning::CounterResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Result: 任务完成后返回的结果\n"
"int32 final_count\n"
;
  }

  static const char* value(const ::ros_base_learning::CounterResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_base_learning::CounterResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.final_count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CounterResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_base_learning::CounterResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_base_learning::CounterResult_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "final_count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.final_count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_BASE_LEARNING_MESSAGE_COUNTERRESULT_H
