; Auto-generated. Do not edit!


(cl:in-package ros_base_learning-msg)


;//! \htmlinclude CounterGoal.msg.html

(cl:defclass <CounterGoal> (roslisp-msg-protocol:ros-message)
  ((target_number
    :reader target_number
    :initarg :target_number
    :type cl:integer
    :initform 0))
)

(cl:defclass CounterGoal (<CounterGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CounterGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CounterGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ros_base_learning-msg:<CounterGoal> is deprecated: use ros_base_learning-msg:CounterGoal instead.")))

(cl:ensure-generic-function 'target_number-val :lambda-list '(m))
(cl:defmethod target_number-val ((m <CounterGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ros_base_learning-msg:target_number-val is deprecated.  Use ros_base_learning-msg:target_number instead.")
  (target_number m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CounterGoal>) ostream)
  "Serializes a message object of type '<CounterGoal>"
  (cl:let* ((signed (cl:slot-value msg 'target_number)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CounterGoal>) istream)
  "Deserializes a message object of type '<CounterGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'target_number) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CounterGoal>)))
  "Returns string type for a message object of type '<CounterGoal>"
  "ros_base_learning/CounterGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CounterGoal)))
  "Returns string type for a message object of type 'CounterGoal"
  "ros_base_learning/CounterGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CounterGoal>)))
  "Returns md5sum for a message object of type '<CounterGoal>"
  "5e5331756d1685bdff28b9bf94bf4c45")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CounterGoal)))
  "Returns md5sum for a message object of type 'CounterGoal"
  "5e5331756d1685bdff28b9bf94bf4c45")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CounterGoal>)))
  "Returns full string definition for message of type '<CounterGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal: 定义我们想让服务器实现的目标~%int32 target_number~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CounterGoal)))
  "Returns full string definition for message of type 'CounterGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal: 定义我们想让服务器实现的目标~%int32 target_number~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CounterGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CounterGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'CounterGoal
    (cl:cons ':target_number (target_number msg))
))
