; Auto-generated. Do not edit!


(cl:in-package ros_base_learning-msg)


;//! \htmlinclude CounterFeedback.msg.html

(cl:defclass <CounterFeedback> (roslisp-msg-protocol:ros-message)
  ((current_number
    :reader current_number
    :initarg :current_number
    :type cl:integer
    :initform 0))
)

(cl:defclass CounterFeedback (<CounterFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CounterFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CounterFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ros_base_learning-msg:<CounterFeedback> is deprecated: use ros_base_learning-msg:CounterFeedback instead.")))

(cl:ensure-generic-function 'current_number-val :lambda-list '(m))
(cl:defmethod current_number-val ((m <CounterFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ros_base_learning-msg:current_number-val is deprecated.  Use ros_base_learning-msg:current_number instead.")
  (current_number m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CounterFeedback>) ostream)
  "Serializes a message object of type '<CounterFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'current_number)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CounterFeedback>) istream)
  "Deserializes a message object of type '<CounterFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'current_number) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CounterFeedback>)))
  "Returns string type for a message object of type '<CounterFeedback>"
  "ros_base_learning/CounterFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CounterFeedback)))
  "Returns string type for a message object of type 'CounterFeedback"
  "ros_base_learning/CounterFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CounterFeedback>)))
  "Returns md5sum for a message object of type '<CounterFeedback>"
  "a34d09927bdf6eea84e4ff079b190b1d")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CounterFeedback)))
  "Returns md5sum for a message object of type 'CounterFeedback"
  "a34d09927bdf6eea84e4ff079b190b1d")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CounterFeedback>)))
  "Returns full string definition for message of type '<CounterFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback: 任务执行过程中周期性返回的数据~%int32 current_number~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CounterFeedback)))
  "Returns full string definition for message of type 'CounterFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback: 任务执行过程中周期性返回的数据~%int32 current_number~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CounterFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CounterFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'CounterFeedback
    (cl:cons ':current_number (current_number msg))
))
